#!/bin/sh -e

SHAKE_ARGS="-j"

if [ -z "`which stack`" ]; then
    case "$1" in
	.update)
	    shift
	    cabal install --only-dependencies "$@"
	    cabal clean
	    ;;
	*) cabal run -- $SHAKE_ARGS "$@"
	    ;;
    esac
else
    stack build
    stack exec -- methcla-shakefile $SHAKE_ARGS "$@"
fi
