#!/bin/sh -e

ENV_FILE="config/env.sh"
SHAKE_ARGS="-j"

# Configure environment
set -a # auto export variables
if [ -f "$ENV_FILE" ]; then
    source "${ENV_FILE}"
fi

if [ -z "`which stack`" ]; then
    case "$1" in
	.update)
	    shift
	    cabal install --only-dependencies "$@"
	    cabal clean
	    ;;
	*) cabal run -- $SHAKE_ARGS "$@"
	    ;;
    esac
else
    stack --install-ghc build
    stack exec -- methcla-shakefile $SHAKE_ARGS "$@"
fi
