#!/bin/bash
# Copyright 2012-2013 Samplecount S.L.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -f "$HOME/.profile" ]; then
    source "$HOME/.profile"
elif [ -f "$HOME/.bash_login" ]; then
    source "$HOME/.bash_login"
fi

# if [ -z "$VIRTHUALENV" -a -f "../.virthualenv/bin/activate" ]; then
#     source "../.virthualenv/bin/activate"
# fi

rtsopts="+RTS -N -RTS"

function shakeit()
{
    ./cabal-dev/bin/shakefile $rtsopts "$@"
}

function shakeit_with_errors()
{
    shakeit "$@" 2>&1 | tee errors.err
    return ${PIPESTATUS[0]}
}

case $1 in
    update) shift ; cabal-dev install "$@" ;;
    *) shakeit "$@" ;;
esac
