#!/bin/bash

if [ -f "$HOME/.profile" ]; then
	source "$HOME/.profile"
elif [ -f "$HOME/.bash_login" ]; then
	source "$HOME/.bash_login"
fi

# if [ -z "$VIRTHUALENV" -a -f "../.virthualenv/bin/activate" ]; then
#     source "../.virthualenv/bin/activate"
# fi

rtsopts="+RTS -N -RTS"

function shakeit()
{
	./cabal-dev/bin/shakefile $rtsopts "$@" 2>&1 | tee errors.err
}

case $1 in
	update) cabal-dev install || exit 1 ;;
	*) shakeit "$@" || exit 1 ;;
esac
