#!/bin/sh

root="$1"
sandbox="`pwd`/.cabal-sandbox"
warp="$sandbox/bin/warp"

if [ ! -d "$sandbox" ]; then
    cabal sandbox init
fi

if [ ! -e "$warp" ]; then
    cabal install -j warp-static
fi

cd "$root" && exec $warp
